export const testData = [
    {
        id: 1,
        title: "Card Title",
        price: 23,
        imgsrc: "https://picsum.photos/id/201/300/200",
        imgalt: "Card Image 1",
    },
    {
        id: 2,
        title: "Card Title",
        price: 23,
        imgsrc: "https://picsum.photos/id/201/300/200",
        imgalt: "Card Image 2",
    },
    {
        id: 3,
        title: "Card Title",
        price: 23,
        imgsrc: "https://picsum.photos/id/201/300/200",
        imgalt: "Card Image 3",
    },
    {
        id: 4,
        title: "Card Title",
        price: 23,
        imgsrc: "https://picsum.photos/id/201/300/200",
        imgalt: "Card Image 4",
    },
    {
        id: 5,
        title: "Card Title",
        price: 23,
        imgsrc: "https://picsum.photos/id/201/300/200",
        imgalt: "Card Image 5",
    },
    {
        id: 6,
        title: "Card Title",
        price: 23,
        imgsrc: "https://picsum.photos/id/201/300/200",
        imgalt: "Card Image 6",
    },
    {
        id: 7,
        title: "Card Title",
        price: 23,
        imgsrc: "https://picsum.photos/id/201/300/200",
        imgalt: "Card Image 7",
    },
    {
        id: 8,
        title: "Card Title",
        price: 23,
        imgsrc: "https://picsum.photos/id/201/300/200",
        imgalt: "Card Image 8",
    },
    {
        id: 9,
        title: "Card Title",
        price: 23,
        imgsrc: "https://picsum.photos/id/201/300/200",
        imgalt: "Card Image 9",
    },
    {
        id: 10,
        title: "Card Title",
        price: 23,
        imgsrc: "https://picsum.photos/id/201/300/200",
        imgalt: "Card Image 10",
    }
]